"""Administrative application service for project grader allocation."""

from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session, selectinload

from auth.utils import utcnow
import db_transaction_manager
from grading_allocation.constants import AllocationCapacity, AllocationScope
from grading_allocation.dtos import (
    AllocationInputDTO,
    AllocationPolicyDTO,
    GraderCandidateDTO,
    GraderAllocationDTO,
    ProjectAllocationStateDTO,
    TargetIdentity,
)
from grading_allocation.exceptions import (
    AllocationConflictError,
    AllocationForbiddenError,
    AllocationNotFoundError,
    GradingAllocationError,
)
from grading_allocation.models import ProjectGraderAllocation, ProjectGradingAllocationPolicy
from grading_allocation.targets import derive_project_targets, target_identity_set
from models import LabUnit, Project, User


MANAGER_ROLES = {"admin", "local_admin", "data_manager"}


def get_project_allocation_state(
    actor_user_id: int,
    project_id: int,
    *,
    include_inactive: bool = False,
) -> ProjectAllocationStateDTO:
    with db_transaction_manager.transaction_scope() as db:
        actor_lab_ids = _require_project_manager(db, actor_user_id, project_id)
        targets, target_warnings = derive_project_targets(db, project_id)
        allocation_query = (
            select(ProjectGraderAllocation)
            .options(
                selectinload(ProjectGraderAllocation.user),
                selectinload(ProjectGraderAllocation.lab_unit),
                selectinload(ProjectGraderAllocation.disease),
                selectinload(ProjectGraderAllocation.encounter_set_type),
            )
            .where(
                ProjectGraderAllocation.project_id == project_id,
                ProjectGraderAllocation.lab_unit_id.in_(actor_lab_ids),
            )
            .order_by(
                ProjectGraderAllocation.active.desc(),
                ProjectGraderAllocation.scope,
                ProjectGraderAllocation.disease_id,
                ProjectGraderAllocation.encounter_set_type_id,
                ProjectGraderAllocation.lab_unit_id,
                ProjectGraderAllocation.user_id,
                ProjectGraderAllocation.capacity,
            )
        )
        if not include_inactive:
            allocation_query = allocation_query.where(ProjectGraderAllocation.active.is_(True))
        allocations = db.execute(allocation_query).scalars().all()
        policy = db.execute(
            select(ProjectGradingAllocationPolicy).where(
                ProjectGradingAllocationPolicy.project_id == project_id
            )
        ).scalar_one_or_none()
        coverage = _coverage(targets=[target.identity for target in targets], allocations=allocations)
        return ProjectAllocationStateDTO(
            project_id=project_id,
            policy=AllocationPolicyDTO(
                project_id=project_id,
                enforcement_enabled=bool(policy and policy.enforcement_enabled),
                updated_at=policy.updated_at if policy else None,
            ),
            targets=tuple(
                {**target.to_dict(), "coverage": coverage[target.identity.key]}
                for target in targets
            ),
            allocations=tuple(_allocation_dto(row) for row in allocations),
            warnings=tuple(
                target_warnings + _readiness_warnings(coverage, allocations)
            ),
        )


def create_or_reactivate_allocation(
    actor_user_id: int,
    project_id: int,
    dto: AllocationInputDTO,
) -> GraderAllocationDTO:
    _validate_target_shape(dto.target)
    try:
        with db_transaction_manager.transaction_scope() as db:
            actor_lab_ids = _require_project_manager(db, actor_user_id, project_id)
            _require_actor_lab(actor_lab_ids, dto.lab_unit_id)
            if dto.target not in target_identity_set(db, project_id):
                raise GradingAllocationError(
                    "The requested grading target is not generated by an active Upload & Grading Profile.",
                    details={"target_key": dto.target.key},
                )
            user = (
                db.execute(
                    select(User)
                    .options(selectinload(User.roles), selectinload(User.lab_units))
                    .where(User.id == dto.user_id)
                )
                .scalars()
                .one_or_none()
            )
            if user is None or not user.is_active:
                raise AllocationNotFoundError("Grader user not found.")
            _validate_user_capacity(user, dto.capacity)

            row = _find_allocation(db, project_id, dto)
            if row is None:
                row = ProjectGraderAllocation(
                    project_id=project_id,
                    user_id=dto.user_id,
                    lab_unit_id=dto.lab_unit_id,
                    scope=dto.scope.value,
                    disease_id=dto.disease_id,
                    encounter_set_type_id=dto.encounter_set_type_id,
                    capacity=dto.capacity.value,
                    active=True,
                    created_by_user_id=actor_user_id,
                    updated_by_user_id=actor_user_id,
                )
                db.add(row)
            else:
                row.active = True
                row.deactivated_at = None
                row.updated_by_user_id = actor_user_id
            db.flush()
            return _allocation_dto(row)
    except IntegrityError as exc:
        raise AllocationConflictError("An equivalent grader allocation already exists.") from exc


def list_grader_candidates(
    actor_user_id: int,
    project_id: int,
    *,
    lab_unit_id: int,
    capacity: AllocationCapacity,
) -> tuple[GraderCandidateDTO, ...]:
    """Return active users who can receive an explicit project allocation."""
    with db_transaction_manager.transaction_scope() as db:
        actor_lab_ids = _require_project_manager(db, actor_user_id, project_id)
        _require_actor_lab(actor_lab_ids, lab_unit_id)
        users = (
            db.execute(
                select(User)
                .options(selectinload(User.roles), selectinload(User.lab_units))
                .where(User.is_active.is_(True))
                .order_by(User.full_name, User.username, User.id)
            )
            .scalars()
            .all()
        )
        return tuple(
            GraderCandidateDTO(
                user_id=user.id,
                username=user.username,
                full_name=user.full_name,
                roles=tuple(sorted(role.name for role in user.roles)),
                is_member_of_lab=lab_unit_id in {lab.id for lab in user.lab_units},
            )
            for user in users
            if _user_has_capacity(user, capacity)
        )


def set_allocation_active(
    actor_user_id: int,
    project_id: int,
    allocation_id: int,
    *,
    active: bool,
) -> GraderAllocationDTO:
    with db_transaction_manager.transaction_scope() as db:
        actor_lab_ids = _require_project_manager(db, actor_user_id, project_id)
        row = db.get(ProjectGraderAllocation, allocation_id)
        if row is None or row.project_id != project_id:
            raise AllocationNotFoundError("Project grader allocation not found.")
        _require_actor_lab(actor_lab_ids, row.lab_unit_id)
        row.active = active
        row.deactivated_at = None if active else utcnow()
        row.updated_by_user_id = actor_user_id
        db.flush()
        return _allocation_dto(row)


def set_project_enforcement(
    actor_user_id: int,
    project_id: int,
    *,
    enabled: bool,
) -> AllocationPolicyDTO:
    with db_transaction_manager.transaction_scope() as db:
        _require_project_manager(db, actor_user_id, project_id)
        targets, target_warnings = derive_project_targets(db, project_id)
        if enabled:
            if not targets:
                raise AllocationConflictError(
                    "Project allocation cannot be enforced without an active grading target."
                )
            if target_warnings:
                raise AllocationConflictError(
                    "Project grading targets contain unresolved configuration.",
                    details={"warnings": target_warnings},
                )
            allocations = (
                db.execute(
                    select(ProjectGraderAllocation)
                    .options(selectinload(ProjectGraderAllocation.lab_unit))
                    .where(
                        ProjectGraderAllocation.project_id == project_id,
                        ProjectGraderAllocation.active.is_(True),
                    )
                )
                .scalars()
                .all()
            )
            coverage = _coverage(
                targets=[target.identity for target in targets],
                allocations=allocations,
            )
            warnings = _readiness_warnings(coverage, allocations)
            if warnings:
                raise AllocationConflictError(
                    "Every active grading target requires resident and arbitrator coverage before enforcement.",
                    details={"warnings": warnings},
                )

        policy = db.execute(
            select(ProjectGradingAllocationPolicy).where(
                ProjectGradingAllocationPolicy.project_id == project_id
            )
        ).scalar_one_or_none()
        if policy is None:
            policy = ProjectGradingAllocationPolicy(
                project_id=project_id,
                enforcement_enabled=enabled,
                created_by_user_id=actor_user_id,
                updated_by_user_id=actor_user_id,
            )
            db.add(policy)
        else:
            policy.enforcement_enabled = enabled
            policy.updated_by_user_id = actor_user_id
        db.flush()
        return AllocationPolicyDTO(
            project_id=project_id,
            enforcement_enabled=policy.enforcement_enabled,
            updated_at=policy.updated_at,
        )


def _require_project_manager(db: Session, actor_user_id: int, project_id: int) -> set[int]:
    project = db.get(Project, project_id)
    if project is None:
        raise AllocationNotFoundError("Project not found.")
    actor = (
        db.execute(
            select(User)
            .options(selectinload(User.roles), selectinload(User.lab_units))
            .where(User.id == actor_user_id)
        )
        .scalars()
        .one_or_none()
    )
    if actor is None or not ({role.name for role in actor.roles} & MANAGER_ROLES):
        raise AllocationForbiddenError("You cannot manage grading allocation for this project.")
    if actor.has_role("admin"):
        return set(db.execute(select(LabUnit.id)).scalars().all())
    lab_ids = {lab.id for lab in actor.lab_units}
    if not lab_ids:
        raise AllocationForbiddenError("You are not assigned to any manageable lab units.")
    return lab_ids


def _require_actor_lab(actor_lab_ids: set[int], lab_unit_id: int) -> None:
    if lab_unit_id not in actor_lab_ids:
        raise AllocationForbiddenError("You cannot manage allocations outside your lab-unit scope.")


def _validate_user_capacity(user: User, capacity: AllocationCapacity) -> None:
    if _user_has_capacity(user, capacity):
        return
    if capacity == AllocationCapacity.RESIDENT:
        raise GradingAllocationError(
            "Resident capacity requires the resident, resident2, or ophthalmologist role."
        )
    raise GradingAllocationError(
        "Arbitrator capacity requires the arbitrator or ophthalmologist role."
    )


def _user_has_capacity(user: User, capacity: AllocationCapacity) -> bool:
    if capacity == AllocationCapacity.RESIDENT:
        return user.has_role("resident", "resident2", "ophthalmologist")
    return user.has_role("arbitrator", "ophthalmologist")


def _validate_target_shape(target: TargetIdentity) -> None:
    if (
        target.scope == AllocationScope.DISEASE_IMAGE
        and target.disease_id is not None
        and target.encounter_set_type_id is None
    ):
        return
    if (
        target.scope == AllocationScope.DISEASE_ENCOUNTER
        and target.disease_id is not None
        and target.encounter_set_type_id is not None
    ):
        return
    if (
        target.scope == AllocationScope.ENCOUNTER_SET_UNIFIED
        and target.disease_id is None
        and target.encounter_set_type_id is not None
    ):
        return
    raise GradingAllocationError("The grading target fields do not match the requested scope.")


def _find_allocation(
    db: Session,
    project_id: int,
    dto: AllocationInputDTO,
) -> ProjectGraderAllocation | None:
    query = select(ProjectGraderAllocation).where(
        ProjectGraderAllocation.project_id == project_id,
        ProjectGraderAllocation.user_id == dto.user_id,
        ProjectGraderAllocation.lab_unit_id == dto.lab_unit_id,
        ProjectGraderAllocation.scope == dto.scope.value,
        ProjectGraderAllocation.capacity == dto.capacity.value,
    )
    query = query.where(
        ProjectGraderAllocation.disease_id.is_(None)
        if dto.disease_id is None
        else ProjectGraderAllocation.disease_id == dto.disease_id,
        ProjectGraderAllocation.encounter_set_type_id.is_(None)
        if dto.encounter_set_type_id is None
        else ProjectGraderAllocation.encounter_set_type_id == dto.encounter_set_type_id,
    )
    return db.execute(query).scalar_one_or_none()


def _allocation_dto(row: ProjectGraderAllocation) -> GraderAllocationDTO:
    return GraderAllocationDTO(
        id=row.id,
        project_id=row.project_id,
        user_id=row.user_id,
        username=row.user.username if row.user else None,
        user_full_name=row.user.full_name if row.user else None,
        lab_unit_id=row.lab_unit_id,
        lab_unit_name=row.lab_unit.name if row.lab_unit else None,
        scope=row.scope,
        disease_id=row.disease_id,
        disease_name=row.disease.name if row.disease else None,
        encounter_set_type_id=row.encounter_set_type_id,
        encounter_set_type_name=row.encounter_set_type.name if row.encounter_set_type else None,
        capacity=row.capacity,
        active=row.active,
        created_at=row.created_at,
        updated_at=row.updated_at,
        deactivated_at=row.deactivated_at,
    )


def _coverage(
    *,
    targets: list[TargetIdentity],
    allocations: list[ProjectGraderAllocation],
) -> dict[str, dict[str, int]]:
    coverage = {
        target.key: {
            AllocationCapacity.RESIDENT.value: 0,
            AllocationCapacity.ARBITRATOR.value: 0,
        }
        for target in targets
    }
    for row in allocations:
        if not row.active:
            continue
        identity = TargetIdentity(
            scope=AllocationScope(row.scope),
            disease_id=row.disease_id,
            encounter_set_type_id=row.encounter_set_type_id,
        )
        if identity.key in coverage and row.capacity in coverage[identity.key]:
            coverage[identity.key][row.capacity] += 1
    return coverage


def _coverage_warnings(coverage: dict[str, dict[str, int]]) -> list[dict[str, object]]:
    warnings: list[dict[str, object]] = []
    for target_key, counts in coverage.items():
        missing = [capacity for capacity, count in counts.items() if count == 0]
        if missing:
            warnings.append(
                {
                    "code": "grading_target_capacity_missing",
                    "target_key": target_key,
                    "missing_capacities": missing,
                    "message": f"Target '{target_key}' has no active {', '.join(missing)} allocation.",
                }
            )
    return warnings


def _readiness_warnings(
    coverage: dict[str, dict[str, int]],
    allocations: list[ProjectGraderAllocation],
) -> list[dict[str, object]]:
    warnings = _coverage_warnings(coverage)
    complete_target_keys = {
        target_key
        for target_key, counts in coverage.items()
        if all(count > 0 for count in counts.values())
    }
    lab_coverage: dict[tuple[str, int], dict[str, object]] = {}
    for row in allocations:
        if not row.active:
            continue
        identity = TargetIdentity(
            scope=AllocationScope(row.scope),
            disease_id=row.disease_id,
            encounter_set_type_id=row.encounter_set_type_id,
        )
        if identity.key not in complete_target_keys:
            continue
        item = lab_coverage.setdefault(
            (identity.key, row.lab_unit_id),
            {
                "lab_unit_name": row.lab_unit.name if row.lab_unit else str(row.lab_unit_id),
                AllocationCapacity.RESIDENT.value: 0,
                AllocationCapacity.ARBITRATOR.value: 0,
            },
        )
        item[row.capacity] = int(item[row.capacity]) + 1

    for (target_key, lab_unit_id), counts in sorted(lab_coverage.items()):
        missing = [
            capacity.value
            for capacity in AllocationCapacity
            if counts[capacity.value] == 0
        ]
        if not missing:
            continue
        lab_unit_name = str(counts["lab_unit_name"])
        warnings.append(
            {
                "code": "grading_target_lab_capacity_missing",
                "target_key": target_key,
                "lab_unit_id": lab_unit_id,
                "missing_capacities": missing,
                "message": (
                    f"Target '{target_key}' in lab '{lab_unit_name}' has no active "
                    f"{', '.join(missing)} allocation."
                ),
            }
        )
    return warnings
