"""Derive project allocation targets from active Upload & Grading Profiles."""

from __future__ import annotations

from collections.abc import Iterable

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from grading_allocation.constants import AllocationScope
from grading_allocation.dtos import ProjectGradingTargetDTO, TargetIdentity
from upload_profiles.models import (
    ProjectUploadProfile,
    UploadProfile,
    UploadProfileDisease,
    UploadProfileEncounterSetType,
    UploadProfileEncounterSetTypeGradingPackage,
    UploadProfileEncounterSetTypeImageGradingScheme,
    UploadProfileEncounterSetTypePackageEncounterScheme,
    UploadProfileEncounterSetTypePackageImageScheme,
)


NON_ENCOUNTER_SET_UPLOAD_KINDS = {"direct_image", "pregraded", "remidio"}


def derive_project_targets(
    db: Session,
    project_id: int,
) -> tuple[list[ProjectGradingTargetDTO], list[dict[str, object]]]:
    """Return the deduplicated semantic targets generated by active profiles."""
    mappings = (
        db.execute(
            select(ProjectUploadProfile)
            .join(ProjectUploadProfile.profile)
            .where(
                ProjectUploadProfile.project_id == project_id,
                ProjectUploadProfile.active.is_(True),
                UploadProfile.active.is_(True),
            )
            .options(
                selectinload(ProjectUploadProfile.profile)
                .selectinload(UploadProfile.diseases)
                .selectinload(UploadProfileDisease.disease),
                selectinload(ProjectUploadProfile.profile).selectinload(
                    UploadProfile.upload_kinds
                ),
                selectinload(ProjectUploadProfile.profile)
                .selectinload(UploadProfile.encounter_set_types)
                .selectinload(UploadProfileEncounterSetType.encounter_set_type),
                selectinload(ProjectUploadProfile.profile)
                .selectinload(UploadProfile.encounter_set_types)
                .selectinload(UploadProfileEncounterSetType.image_grading_schemes)
                .selectinload(UploadProfileEncounterSetTypeImageGradingScheme.disease),
                selectinload(ProjectUploadProfile.profile)
                .selectinload(UploadProfile.encounter_set_types)
                .selectinload(UploadProfileEncounterSetType.grading_packages)
                .selectinload(UploadProfileEncounterSetTypeGradingPackage.image_grading_schemes)
                .selectinload(UploadProfileEncounterSetTypePackageImageScheme.disease),
                selectinload(ProjectUploadProfile.profile)
                .selectinload(UploadProfile.encounter_set_types)
                .selectinload(UploadProfileEncounterSetType.grading_packages)
                .selectinload(UploadProfileEncounterSetTypeGradingPackage.encounter_grading_schemes)
                .selectinload(UploadProfileEncounterSetTypePackageEncounterScheme.disease),
                selectinload(ProjectUploadProfile.profile)
                .selectinload(UploadProfile.encounter_set_types)
                .selectinload(UploadProfileEncounterSetType.grading_packages)
                .selectinload(UploadProfileEncounterSetTypeGradingPackage.default_image_grading_scheme),
            )
            .order_by(UploadProfile.name, ProjectUploadProfile.id)
        )
        .scalars()
        .all()
    )

    targets: dict[TargetIdentity, ProjectGradingTargetDTO] = {}
    warnings: list[dict[str, object]] = []
    for mapping in mappings:
        profile = mapping.profile
        upload_kinds = {row.upload_kind for row in profile.upload_kinds}
        if not upload_kinds or upload_kinds.intersection(NON_ENCOUNTER_SET_UPLOAD_KINDS):
            for profile_disease in profile.diseases:
                _add_disease_image_target(
                    targets,
                    profile_id=profile.id,
                    profile_name=profile.name,
                    disease_id=profile_disease.disease_id,
                    disease_name=profile_disease.disease.name,
                )

        for est_config in profile.encounter_set_types:
            if not est_config.active:
                continue
            est = est_config.encounter_set_type
            active_packages = [package for package in est_config.grading_packages if package.active]
            if not active_packages:
                if est_config.encounter_grading_scheme_id:
                    _add_unified_target(
                        targets,
                        profile_id=profile.id,
                        profile_name=profile.name,
                        encounter_set_type_id=est.id,
                        encounter_set_type_name=est.name,
                        grading_scheme_ids=(
                            [
                                row.disease_id
                                for row in est_config.image_grading_schemes
                                if row.active
                            ]
                            + [est_config.encounter_grading_scheme_id]
                        ),
                    )
                else:
                    for image_scheme in est_config.image_grading_schemes:
                        if image_scheme.active:
                            _add_disease_encounter_set_target(
                                targets,
                                profile_id=profile.id,
                                profile_name=profile.name,
                                disease_id=image_scheme.disease_id,
                                disease_name=image_scheme.disease.name,
                                encounter_set_type_id=est.id,
                                encounter_set_type_name=est.name,
                                grading_scheme_ids=[image_scheme.disease_id],
                            )
                continue

            for package in active_packages:
                active_image_schemes = [row for row in package.image_grading_schemes if row.active]
                encounter_scheme_ids = [
                    row.disease_id for row in package.encounter_grading_schemes if row.active
                ]
                if not active_image_schemes and not encounter_scheme_ids:
                    continue
                if package.grading_mode == "unified":
                    _add_unified_target(
                        targets,
                        profile_id=profile.id,
                        profile_name=profile.name,
                        encounter_set_type_id=est.id,
                        encounter_set_type_name=est.name,
                        grading_scheme_ids=(
                            [row.disease_id for row in active_image_schemes]
                            + encounter_scheme_ids
                        ),
                    )
                    continue

                if not active_image_schemes:
                    warnings.append(
                        {
                            "code": "disease_encounter_context_missing",
                            "profile_id": profile.id,
                            "package_id": package.id,
                            "message": (
                                f"Package '{package.name}' is disease-specific but has no active "
                                "image grading scheme to identify its disease."
                            ),
                        }
                    )
                    continue
                for image_scheme in active_image_schemes:
                    _add_disease_encounter_set_target(
                        targets,
                        profile_id=profile.id,
                        profile_name=profile.name,
                        disease_id=image_scheme.disease_id,
                        disease_name=image_scheme.disease.name,
                        encounter_set_type_id=est.id,
                        encounter_set_type_name=est.name,
                        grading_scheme_ids=[image_scheme.disease_id] + encounter_scheme_ids,
                    )

    return sorted(targets.values(), key=lambda target: (target.label.lower(), target.identity.key)), warnings


def target_identity_set(db: Session, project_id: int) -> set[TargetIdentity]:
    targets, _warnings = derive_project_targets(db, project_id)
    return {target.identity for target in targets}


def _add_disease_image_target(
    targets: dict[TargetIdentity, ProjectGradingTargetDTO],
    *,
    profile_id: int,
    profile_name: str,
    disease_id: int,
    disease_name: str,
) -> None:
    identity = TargetIdentity(AllocationScope.DISEASE_IMAGE, disease_id=disease_id)
    target = targets.setdefault(
        identity,
        ProjectGradingTargetDTO(
            identity=identity,
            label=f"{disease_name} / Non-EncounterSet Images",
            disease_name=disease_name,
        ),
    )
    target.source_profiles[profile_id] = profile_name
    target.grading_scheme_ids.add(disease_id)


def _add_disease_encounter_set_target(
    targets: dict[TargetIdentity, ProjectGradingTargetDTO],
    *,
    profile_id: int,
    profile_name: str,
    disease_id: int,
    disease_name: str,
    encounter_set_type_id: int,
    encounter_set_type_name: str,
    grading_scheme_ids: Iterable[int],
) -> None:
    identity = TargetIdentity(
        AllocationScope.DISEASE_ENCOUNTER,
        disease_id=disease_id,
        encounter_set_type_id=encounter_set_type_id,
    )
    target = targets.setdefault(
        identity,
        ProjectGradingTargetDTO(
            identity=identity,
            label=f"{disease_name} / EncounterSet ({encounter_set_type_name})",
            disease_name=disease_name,
            encounter_set_type_name=encounter_set_type_name,
        ),
    )
    target.source_profiles[profile_id] = profile_name
    target.grading_scheme_ids.update(grading_scheme_ids)


def _add_unified_target(
    targets: dict[TargetIdentity, ProjectGradingTargetDTO],
    *,
    profile_id: int,
    profile_name: str,
    encounter_set_type_id: int,
    encounter_set_type_name: str,
    grading_scheme_ids: Iterable[int],
) -> None:
    identity = TargetIdentity(
        AllocationScope.ENCOUNTER_SET_UNIFIED,
        encounter_set_type_id=encounter_set_type_id,
    )
    target = targets.setdefault(
        identity,
        ProjectGradingTargetDTO(
            identity=identity,
            label=f"Unified EncounterSet ({encounter_set_type_name})",
            encounter_set_type_name=encounter_set_type_name,
        ),
    )
    target.source_profiles[profile_id] = profile_name
    target.grading_scheme_ids.update(grading_scheme_ids)
