"""Lean, role-bound authorization and SQL scoping helpers."""

from authz.context import AccessContext, access_context, clear_access_context
from authz.exceptions import AuthorizationDenied
from authz.rows import (
    RecordColumns,
    admin_rows,
    assigned_lab_rows,
    hospital_rows,
    hospital_choice_rows,
    lab_unit_choice_rows,
    project_rows,
    role_scoped_rows,
    self_rows,
    where_all,
    where_any,
)
from authz.scopes import (
    RecordScope,
    RecordWorld,
    ScopeCheck,
    admin_scope,
    assigned_lab_scope,
    grading_scope,
    hospital_scope,
    project_scope,
    project_wide_scope,
    require_all,
    require_any,
    self_scope,
    upload_scope,
)

__all__ = [
    "AccessContext",
    "AuthorizationDenied",
    "RecordColumns",
    "RecordScope",
    "RecordWorld",
    "ScopeCheck",
    "access_context",
    "admin_rows",
    "admin_scope",
    "assigned_lab_rows",
    "assigned_lab_scope",
    "clear_access_context",
    "grading_scope",
    "hospital_rows",
    "hospital_choice_rows",
    "hospital_scope",
    "project_rows",
    "lab_unit_choice_rows",
    "project_scope",
    "project_wide_scope",
    "require_all",
    "require_any",
    "role_scoped_rows",
    "self_rows",
    "self_scope",
    "upload_scope",
    "where_all",
    "where_any",
]
