"""Add unique constraint on encounter_set_image position

Revision ID: 2a251986df60
Revises: 198d644ccbce
Create Date: 2026-02-01 04:09:15.469052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a251986df60'
down_revision: Union[str, Sequence[str], None] = '198d644ccbce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy.engine.reflection import Inspector

    # Add unique constraint on encounter_set_images (idempotent)
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if constraint already exists
    constraints = [c['name'] for c in inspector.get_unique_constraints('encounter_set_images')]
    if 'uq_encounter_set_image_position' not in constraints:
        op.create_unique_constraint(
            'uq_encounter_set_image_position',
            'encounter_set_images',
            ['patient_encounter_id', 'spatial_position']
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_gradings_archive')
    op.drop_index(op.f('idx_mv_refresh_log_completed_at'), table_name='materialized_view_refresh_log')
    op.drop_index(op.f('idx_mv_refresh_log_success'), table_name='materialized_view_refresh_log')
    op.drop_index(op.f('idx_mv_refresh_log_view_name'), table_name='materialized_view_refresh_log')
    op.drop_table('materialized_view_refresh_log')
    op.drop_constraint(op.f('uq_dataset_exports_job_id'), 'dataset_exports', type_='unique')
    op.drop_constraint(op.f('uq_dataset_shares_token_hash'), 'dataset_shares', type_='unique')
    op.create_index(op.f('ix_dataset_shares_created_by_user_id'), 'dataset_shares', ['created_by_user_id'], unique=False)
    op.drop_index(op.f('idx_email_settings_password_salt'), table_name='email_settings')
    op.create_index(op.f('ix_encounter_set_images_hospital_id'), 'encounter_set_images', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_encounter_set_images_s3_config_id'), 'encounter_set_images', ['s3_config_id'], unique=False)
    op.create_index(op.f('ix_image_metadata_backfill_jobs_created_at'), 'image_metadata_backfill_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_metadata_backfill_jobs_created_by_id'), 'image_metadata_backfill_jobs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_image_metadata_backfill_jobs_created_by_username'), 'image_metadata_backfill_jobs', ['created_by_username'], unique=False)
    op.create_index(op.f('ix_image_metadata_backfill_jobs_hospital_id'), 'image_metadata_backfill_jobs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_linked_disease_gradings_linked_disease_id'), 'linked_disease_gradings', ['linked_disease_id'], unique=False)
    op.create_index(op.f('ix_linked_disease_gradings_primary_disease_id'), 'linked_disease_gradings', ['primary_disease_id'], unique=False)
    op.create_index(op.f('ix_pii_detection_jobs_created_at'), 'pii_detection_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_backfill_jobs_created_by_username'), 'task_backfill_jobs', ['created_by_username'], unique=False)
    op.create_index('ix_task_backfill_jobs_hospital_created', 'task_backfill_jobs', ['hospital_id', 'created_at'], unique=False)
    op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    op.alter_column('users', 'is_master_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('users_hospital_id_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    from sqlalchemy.engine.reflection import Inspector

    # Remove unique constraint on encounter_set_images (idempotent)
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    constraints = [c['name'] for c in inspector.get_unique_constraints('encounter_set_images')]
    if 'uq_encounter_set_image_position' in constraints:
        op.drop_constraint('uq_encounter_set_image_position', 'encounter_set_images', type_='unique')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_hospital_id_fkey'), 'users', 'hospitals', ['hospital_id'], ['id'])
    op.alter_column('users', 'is_master_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.drop_index('ix_task_backfill_jobs_hospital_created', table_name='task_backfill_jobs')
    op.drop_index(op.f('ix_task_backfill_jobs_created_by_username'), table_name='task_backfill_jobs')
    op.drop_index(op.f('ix_pii_detection_jobs_created_at'), table_name='pii_detection_jobs')
    op.drop_index(op.f('ix_linked_disease_gradings_primary_disease_id'), table_name='linked_disease_gradings')
    op.drop_index(op.f('ix_linked_disease_gradings_linked_disease_id'), table_name='linked_disease_gradings')
    op.drop_index(op.f('ix_image_metadata_backfill_jobs_hospital_id'), table_name='image_metadata_backfill_jobs')
    op.drop_index(op.f('ix_image_metadata_backfill_jobs_created_by_username'), table_name='image_metadata_backfill_jobs')
    op.drop_index(op.f('ix_image_metadata_backfill_jobs_created_by_id'), table_name='image_metadata_backfill_jobs')
    op.drop_index(op.f('ix_image_metadata_backfill_jobs_created_at'), table_name='image_metadata_backfill_jobs')
    op.drop_index(op.f('ix_encounter_set_images_s3_config_id'), table_name='encounter_set_images')
    op.drop_index(op.f('ix_encounter_set_images_hospital_id'), table_name='encounter_set_images')
    op.create_index(op.f('idx_email_settings_password_salt'), 'email_settings', ['password_salt'], unique=False)
    op.drop_index(op.f('ix_dataset_shares_created_by_user_id'), table_name='dataset_shares')
    op.create_unique_constraint(op.f('uq_dataset_shares_token_hash'), 'dataset_shares', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_dataset_exports_job_id'), 'dataset_exports', ['job_id'], postgresql_nulls_not_distinct=False)
    op.create_table('materialized_view_refresh_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('materialized_view_name', sa.VARCHAR(length=255), server_default=sa.text("'mvw_grading_data_all'::character varying"), autoincrement=False, nullable=False),
    sa.Column('refresh_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('refresh_started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('refresh_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('refresh_duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('materialized_view_refresh_log_pkey'))
    )
    op.create_index(op.f('idx_mv_refresh_log_view_name'), 'materialized_view_refresh_log', ['materialized_view_name'], unique=False)
    op.create_index(op.f('idx_mv_refresh_log_success'), 'materialized_view_refresh_log', ['success'], unique=False)
    op.create_index(op.f('idx_mv_refresh_log_completed_at'), 'materialized_view_refresh_log', ['refresh_completed_at'], unique=False)
    op.create_table('image_gradings_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('encounter_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('direct_image_upload_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grader_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grader_username', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('grader_role', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('graded_for', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('impression', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    comment='Archive of legacy ImageGrading data before migration to Grade model. Created on 2025-11-09'
    )
    # ### end Alembic commands ###
