"""Initial migration

Revision ID: 5a49784f68f1
Revises: 
Create Date: 2025-11-03 11:51:35.276568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a49784f68f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_ai_models_name_version')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ip_locks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', name='uq_iplock_ip')
    )
    op.create_index(op.f('ix_ip_locks_ip_address'), 'ip_locks', ['ip_address'], unique=True)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username_input', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index('ix_login_attempts_ip_created', 'login_attempts', ['ip_address', 'created_at'], unique=False)
    op.create_index('ix_login_attempts_username_created', 'login_attempts', ['username_input', 'created_at'], unique=False)
    op.create_table('password_reset_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_attempts_attempted_at'), 'password_reset_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_password_reset_attempts_email'), 'password_reset_attempts', ['email'], unique=False)
    op.create_index('ix_password_reset_attempts_email_date', 'password_reset_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('ix_password_reset_attempts_ip_date', 'password_reset_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('year_of_joining', sa.Integer(), nullable=True),
    sa.Column('last_date_of_service', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_upload_quota', sa.Integer(), nullable=False),
    sa.Column('file_upload_count', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('zip_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_filename', sa.String(), nullable=False),
    sa.Column('md5_hash', sa.String(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('md5_hash'),
    sa.UniqueConstraint('zip_filename')
    )
    op.create_table('ad_hoc_task_creations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diseases_json', sa.Text(), nullable=False),
    sa.Column('max_images', sa.Integer(), nullable=False),
    sa.Column('filters_json', sa.Text(), nullable=False),
    sa.Column('selected_image_refs_json', sa.Text(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('randomized', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_hoc_task_creations_created_at'), 'ad_hoc_task_creations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ad_hoc_task_creations_created_by_id'), 'ad_hoc_task_creations', ['created_by_id'], unique=False)
    op.create_table('disease_gradings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('impression', sa.String(length=64), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('guidelines', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'impression', name='uq_disease_grading_disease_impression')
    )
    op.create_index('ix_disease_gradings_disease_order', 'disease_gradings', ['disease_id', 'display_order'], unique=False)
    op.create_table('flask_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_flask_sessions_expiry'), 'flask_sessions', ['expiry'], unique=False)
    op.create_index(op.f('ix_flask_sessions_user_id'), 'flask_sessions', ['user_id'], unique=False)
    op.create_table('lab_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'hospital_id', name='uq_labunit_name_per_hospital')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_sender_user_id'), 'notifications', ['sender_user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index('ix_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user', 'user_roles', ['user_id'], unique=False)
    op.create_table('viewer_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('loupe_size', sa.Integer(), nullable=False),
    sa.Column('loupe_zoom', sa.Float(), nullable=False),
    sa.Column('loupe_enabled', sa.Boolean(), nullable=False),
    sa.Column('zoom', sa.Integer(), nullable=False),
    sa.Column('pan_x', sa.Integer(), nullable=False),
    sa.Column('pan_y', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=False),
    sa.Column('contrast', sa.Float(), nullable=False),
    sa.Column('filter', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("filter IN ('none','redfree','greenboost','bluemono','gray','contrast')", name='ck_viewer_presets_filter'),
    sa.CheckConstraint('brightness >= 0.5 AND brightness <= 1.5', name='ck_viewer_presets_brightness'),
    sa.CheckConstraint('contrast >= 0.5 AND contrast <= 1.5', name='ck_viewer_presets_contrast'),
    sa.CheckConstraint('loupe_size >= 100 AND loupe_size <= 500', name='ck_viewer_presets_loupe_size'),
    sa.CheckConstraint('loupe_zoom >= 1.0 AND loupe_zoom <= 4.0', name='ck_viewer_presets_loupe_zoom'),
    sa.CheckConstraint('pan_x >= -600 AND pan_x <= 600', name='ck_viewer_presets_pan_x'),
    sa.CheckConstraint('pan_y >= -600 AND pan_y <= 600', name='ck_viewer_presets_pan_y'),
    sa.CheckConstraint('slot_number >= 1 AND slot_number <= 5', name='ck_viewer_presets_slot_number'),
    sa.CheckConstraint('zoom >= 40 AND zoom <= 500', name='ck_viewer_presets_zoom'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_number', name='uq_viewer_presets_user_slot')
    )
    op.create_index(op.f('ix_viewer_presets_user_id'), 'viewer_presets', ['user_id'], unique=False)
    op.create_table('viewer_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loupe_size', sa.Integer(), nullable=False),
    sa.Column('loupe_zoom', sa.Float(), nullable=False),
    sa.Column('loupe_enabled', sa.Boolean(), nullable=False),
    sa.Column('zoom', sa.Integer(), nullable=False),
    sa.Column('pan_x', sa.Integer(), nullable=False),
    sa.Column('pan_y', sa.Integer(), nullable=False),
    sa.Column('brightness', sa.Float(), nullable=False),
    sa.Column('contrast', sa.Float(), nullable=False),
    sa.Column('filter', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("filter IN ('none','redfree','greenboost','bluemono','gray','contrast')", name='ck_viewer_settings_filter'),
    sa.CheckConstraint('brightness >= 0.5 AND brightness <= 1.5', name='ck_viewer_settings_brightness'),
    sa.CheckConstraint('contrast >= 0.5 AND contrast <= 1.5', name='ck_viewer_settings_contrast'),
    sa.CheckConstraint('loupe_size >= 100 AND loupe_size <= 500', name='ck_viewer_settings_loupe_size'),
    sa.CheckConstraint('loupe_zoom >= 1.0 AND loupe_zoom <= 4.0', name='ck_viewer_settings_loupe_zoom'),
    sa.CheckConstraint('pan_x >= -600 AND pan_x <= 600', name='ck_viewer_settings_pan_x'),
    sa.CheckConstraint('pan_y >= -600 AND pan_y <= 600', name='ck_viewer_settings_pan_y'),
    sa.CheckConstraint('zoom >= 40 AND zoom <= 500', name='ck_viewer_settings_zoom'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewer_settings_user_id'), 'viewer_settings', ['user_id'], unique=True)
    op.create_table('direct_image_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('edited_filename', sa.String(length=255), nullable=True),
    sa.Column('folder_rel', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('lab_unit_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('is_mydriatic', sa.Boolean(), nullable=False),
    sa.Column('is_pregraded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("edited_filename IS NULL OR position('/' in edited_filename) = 0", name='ck_diu_edited_filename_no_slash'),
    sa.CheckConstraint("position('/' in filename) = 0", name='ck_diu_filename_no_slash'),
    sa.CheckConstraint("position('\\\\' in folder_rel) = 0", name='ck_diu_folder_no_backslash'),
    sa.CheckConstraint("substring(folder_rel, 1, 1) <> '/'", name='ck_diu_folder_not_absolute'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_image_uploads_created_at'), 'direct_image_uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_direct_image_uploads_file_hash'), 'direct_image_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_direct_image_uploads_folder_rel'), 'direct_image_uploads', ['folder_rel'], unique=False)
    op.create_index(op.f('ix_direct_image_uploads_uploader_id'), 'direct_image_uploads', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_direct_image_uploads_uuid'), 'direct_image_uploads', ['uuid'], unique=True)
    op.create_index('ix_diu_content_hash', 'direct_image_uploads', ['content_hash'], unique=False)
    op.create_index('ix_diu_folder_created', 'direct_image_uploads', ['folder_rel', 'created_at'], unique=False)
    op.create_index('ix_diu_is_pregraded', 'direct_image_uploads', ['is_pregraded'], unique=False)
    op.create_index('ix_diu_uploader_created', 'direct_image_uploads', ['uploader_id', 'created_at'], unique=False)
    op.create_table('gradings_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_grading_id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['disease_grading_id'], ['disease_gradings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_grading_id', 'sr_no', name='uq_gradings_features_order')
    )
    op.create_index(op.f('ix_gradings_features_disease_grading_id'), 'gradings_features', ['disease_grading_id'], unique=False)
    op.create_index('ix_gradings_features_grading_order', 'gradings_features', ['disease_grading_id', 'sr_no'], unique=False)
    op.create_table('intra_rater_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('lab_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cooldown_days_override', sa.Integer(), nullable=True),
    sa.Column('target_images_per_grader', sa.Integer(), nullable=False),
    sa.Column('normal_grade_id', sa.Integer(), nullable=True),
    sa.Column('selection_snapshot_json', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.ForeignKeyConstraint(['normal_grade_id'], ['disease_gradings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intra_rater_batches_created_at'), 'intra_rater_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_intra_rater_batches_created_by_user_id'), 'intra_rater_batches', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_batches_disease_id'), 'intra_rater_batches', ['disease_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_batches_lab_unit_id'), 'intra_rater_batches', ['lab_unit_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_batches_normal_grade_id'), 'intra_rater_batches', ['normal_grade_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rejected_summary', sa.Text(), nullable=True),
    sa.Column('excel_filename', sa.String(length=255), nullable=True),
    sa.Column('upload_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploader_user_id', sa.Integer(), nullable=True),
    sa.Column('uploader_username', sa.String(length=150), nullable=True),
    sa.Column('uploader_ip', sa.String(length=64), nullable=True),
    sa.Column('lab_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_jobs_lab_unit_id'), 'jobs', ['lab_unit_id'], unique=False)
    op.create_index(op.f('ix_jobs_uploader_user_id'), 'jobs', ['uploader_user_id'], unique=False)
    op.create_index(op.f('ix_jobs_uploader_username'), 'jobs', ['uploader_username'], unique=False)
    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_notification_reads_notification_user')
    )
    op.create_index(op.f('ix_notification_reads_notification_id'), 'notification_reads', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notification_reads_user_id'), 'notification_reads', ['user_id'], unique=False)
    op.create_table('patient_encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('capture_date', sa.String(), nullable=False),
    sa.Column('glaucoma_verified_status', sa.String(length=32), nullable=True),
    sa.Column('glaucoma_verified_by', sa.String(length=150), nullable=True),
    sa.Column('glaucoma_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dr_verified_status', sa.String(length=32), nullable=True),
    sa.Column('dr_verified_by', sa.String(length=150), nullable=True),
    sa.Column('dr_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capture_date_dt', sa.Date(), nullable=True),
    sa.Column('lab_unit_id', sa.Integer(), nullable=True),
    sa.Column('encounter_verified_status', sa.String(length=32), nullable=True),
    sa.Column('encounter_verified_by', sa.String(length=150), nullable=True),
    sa.Column('encounter_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.ForeignKeyConstraint(['zip_file_id'], ['zip_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zip_file_id')
    )
    op.create_index(op.f('ix_patient_encounters_capture_date_dt'), 'patient_encounters', ['capture_date_dt'], unique=False)
    op.create_index(op.f('ix_patient_encounters_dr_verified_status'), 'patient_encounters', ['dr_verified_status'], unique=False)
    op.create_index(op.f('ix_patient_encounters_encounter_verified_status'), 'patient_encounters', ['encounter_verified_status'], unique=False)
    op.create_index(op.f('ix_patient_encounters_glaucoma_verified_status'), 'patient_encounters', ['glaucoma_verified_status'], unique=False)
    op.create_index(op.f('ix_patient_encounters_lab_unit_id'), 'patient_encounters', ['lab_unit_id'], unique=False)
    op.create_table('user_disease_unit_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('lab_unit_id', sa.Integer(), nullable=False),
    sa.Column('can_grade_resident', sa.Boolean(), nullable=False),
    sa.Column('can_grade_resident2', sa.Boolean(), nullable=False),
    sa.Column('can_arbitrate', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(can_grade_resident = true) OR (can_grade_resident2 = true) OR (can_arbitrate = true)', name='ck_user_dur_has_any_permission'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'disease_id', 'lab_unit_id', name='uq_user_disease_unit_role')
    )
    op.create_index(op.f('ix_user_disease_unit_role_disease_id'), 'user_disease_unit_role', ['disease_id'], unique=False)
    op.create_index(op.f('ix_user_disease_unit_role_lab_unit_id'), 'user_disease_unit_role', ['lab_unit_id'], unique=False)
    op.create_index(op.f('ix_user_disease_unit_role_user_id'), 'user_disease_unit_role', ['user_id'], unique=False)
    op.create_index('ix_user_dur_unit_disease', 'user_disease_unit_role', ['lab_unit_id', 'disease_id'], unique=False)
    op.create_index('ix_user_dur_user_active', 'user_disease_unit_role', ['user_id', 'active'], unique=False)
    op.create_table('user_lab_units',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lab_unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lab_unit_id')
    )
    op.create_table('diabetic_retinopathy_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_encounter_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('qualitative_result', sa.String(), nullable=True),
    sa.Column('report_file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_encounter_id'], ['patient_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetic_retinopathy_reports_uuid'), 'diabetic_retinopathy_reports', ['uuid'], unique=True)
    op.create_table('direct_image_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_upload_id', sa.Integer(), nullable=False),
    sa.Column('verified_status', sa.String(length=32), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verified_status IN ('verified', 'unverified', 'pending')", name='ck_di_verify_status'),
    sa.ForeignKeyConstraint(['image_upload_id'], ['direct_image_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_upload_id', name='uq_direct_image_verify_upload_id')
    )
    op.create_index(op.f('ix_direct_image_verifications_image_upload_id'), 'direct_image_verifications', ['image_upload_id'], unique=False)
    op.create_index(op.f('ix_direct_image_verifications_verified_by_id'), 'direct_image_verifications', ['verified_by_id'], unique=False)
    op.create_index(op.f('ix_direct_image_verifications_verified_status'), 'direct_image_verifications', ['verified_status'], unique=False)
    op.create_table('encounter_file_pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_encounter_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('ocr_processed', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('eye_side', sa.String(length=16), nullable=True),
    sa.Column('lab_unit_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("file_type = 'pdf'", name='ck_encounter_file_pdf_only'),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.ForeignKeyConstraint(['patient_encounter_id'], ['patient_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_file_pdfs_eye_side'), 'encounter_file_pdfs', ['eye_side'], unique=False)
    op.create_index(op.f('ix_encounter_file_pdfs_lab_unit_id'), 'encounter_file_pdfs', ['lab_unit_id'], unique=False)
    op.create_index('ix_encounter_file_pdfs_patient_encounter_id', 'encounter_file_pdfs', ['patient_encounter_id'], unique=False)
    op.create_index(op.f('ix_encounter_file_pdfs_uuid'), 'encounter_file_pdfs', ['uuid'], unique=True)
    op.create_table('encounter_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_encounter_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('ocr_processed', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('eye_side', sa.String(length=16), nullable=True),
    sa.Column('lab_unit_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("file_type != 'pdf'", name='ck_encounter_file_not_pdf'),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.ForeignKeyConstraint(['patient_encounter_id'], ['patient_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounter_files_eye_side'), 'encounter_files', ['eye_side'], unique=False)
    op.create_index(op.f('ix_encounter_files_lab_unit_id'), 'encounter_files', ['lab_unit_id'], unique=False)
    op.create_index(op.f('ix_encounter_files_uuid'), 'encounter_files', ['uuid'], unique=True)
    op.create_table('glaucoma_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_encounter_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('vcdr_right', sa.String(), nullable=True),
    sa.Column('vcdr_left', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('qualitative_result', sa.String(), nullable=True),
    sa.Column('report_file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_encounter_id'], ['patient_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glaucoma_reports_uuid'), 'glaucoma_reports', ['uuid'], unique=True)
    op.create_table('job_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploader_user_id', sa.Integer(), nullable=True),
    sa.Column('uploader_username', sa.String(length=150), nullable=True),
    sa.Column('uploader_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_items_job_id'), 'job_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_items_uploader_user_id'), 'job_items', ['uploader_user_id'], unique=False)
    op.create_index(op.f('ix_job_items_uploader_username'), 'job_items', ['uploader_username'], unique=False)
    op.create_table('glaucoma_results_cleaned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glaucoma_report_id', sa.Integer(), nullable=False),
    sa.Column('patient_encounter_id', sa.Integer(), nullable=False),
    sa.Column('vcdr_right_num', sa.Float(), nullable=True),
    sa.Column('vcdr_left_num', sa.Float(), nullable=True),
    sa.Column('original_vcdr_right', sa.String(), nullable=True),
    sa.Column('original_vcdr_left', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('qualitative_result', sa.String(), nullable=True),
    sa.Column('report_uuid', sa.String(length=36), nullable=True),
    sa.Column('report_file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['glaucoma_report_id'], ['glaucoma_reports.id'], ),
    sa.ForeignKeyConstraint(['patient_encounter_id'], ['patient_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glaucoma_results_cleaned_glaucoma_report_id'), 'glaucoma_results_cleaned', ['glaucoma_report_id'], unique=True)
    op.create_index(op.f('ix_glaucoma_results_cleaned_patient_encounter_id'), 'glaucoma_results_cleaned', ['patient_encounter_id'], unique=False)
    op.create_index(op.f('ix_glaucoma_results_cleaned_report_uuid'), 'glaucoma_results_cleaned', ['report_uuid'], unique=False)
    op.create_table('grading_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('encounter_file_id', sa.Integer(), nullable=True),
    sa.Column('direct_image_upload_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('lab_unit_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ad_hoc_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("state IN ('pending','resident_done','resident2_done','arbitration','final')", name='ck_task_state_valid'),
    sa.CheckConstraint('(encounter_file_id IS NOT NULL AND direct_image_upload_id IS NULL) OR (encounter_file_id IS NULL AND direct_image_upload_id IS NOT NULL)', name='ck_grading_task_either_encounter_or_direct'),
    sa.ForeignKeyConstraint(['ad_hoc_id'], ['ad_hoc_task_creations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['direct_image_upload_id'], ['direct_image_uploads.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['encounter_file_id'], ['encounter_files.id'], ),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direct_image_upload_id', 'disease_id', name='uq_task_direct_disease'),
    sa.UniqueConstraint('encounter_file_id', 'disease_id', name='uq_task_encounter_disease')
    )
    op.create_index(op.f('ix_grading_tasks_ad_hoc_id'), 'grading_tasks', ['ad_hoc_id'], unique=False)
    op.create_index(op.f('ix_grading_tasks_direct_image_upload_id'), 'grading_tasks', ['direct_image_upload_id'], unique=False)
    op.create_index(op.f('ix_grading_tasks_disease_id'), 'grading_tasks', ['disease_id'], unique=False)
    op.create_index(op.f('ix_grading_tasks_encounter_file_id'), 'grading_tasks', ['encounter_file_id'], unique=False)
    op.create_index(op.f('ix_grading_tasks_lab_unit_id'), 'grading_tasks', ['lab_unit_id'], unique=False)
    op.create_index(op.f('ix_grading_tasks_state'), 'grading_tasks', ['state'], unique=False)
    op.create_index(op.f('ix_grading_tasks_uuid'), 'grading_tasks', ['uuid'], unique=True)
    op.create_index('ix_task_disease_lab_state', 'grading_tasks', ['disease_id', 'lab_unit_id', 'state'], unique=False)
    op.create_table('image_gradings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_file_id', sa.Integer(), nullable=True),
    sa.Column('direct_image_upload_id', sa.Integer(), nullable=True),
    sa.Column('grader_user_id', sa.Integer(), nullable=True),
    sa.Column('grader_username', sa.String(length=150), nullable=True),
    sa.Column('grader_role', sa.String(length=32), nullable=True),
    sa.Column('graded_for', sa.String(length=32), nullable=False),
    sa.Column('impression', sa.String(length=32), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(encounter_file_id IS NOT NULL AND direct_image_upload_id IS NULL) OR (encounter_file_id IS NULL AND direct_image_upload_id IS NOT NULL)', name='ck_image_grading_either_encounter_or_direct'),
    sa.ForeignKeyConstraint(['direct_image_upload_id'], ['direct_image_uploads.id'], ),
    sa.ForeignKeyConstraint(['encounter_file_id'], ['encounter_files.id'], ),
    sa.ForeignKeyConstraint(['grader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_gradings_direct_image_upload_id'), 'image_gradings', ['direct_image_upload_id'], unique=False)
    op.create_index('ix_image_gradings_direct_user_role_for', 'image_gradings', ['direct_image_upload_id', 'grader_user_id', 'grader_role', 'graded_for'], unique=False)
    op.create_index(op.f('ix_image_gradings_encounter_file_id'), 'image_gradings', ['encounter_file_id'], unique=False)
    op.create_index(op.f('ix_image_gradings_graded_for'), 'image_gradings', ['graded_for'], unique=False)
    op.create_index(op.f('ix_image_gradings_grader_role'), 'image_gradings', ['grader_role'], unique=False)
    op.create_index(op.f('ix_image_gradings_grader_user_id'), 'image_gradings', ['grader_user_id'], unique=False)
    op.create_index('ix_image_gradings_image_user_role_for', 'image_gradings', ['encounter_file_id', 'grader_user_id', 'grader_role', 'graded_for'], unique=False)
    op.create_table('consensus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('final_disease_grading_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_disease_name', sa.String(length=255), nullable=True),
    sa.Column('final_grade_name', sa.String(length=64), nullable=True),
    sa.Column('final_grade_description', sa.Text(), nullable=True),
    sa.CheckConstraint("method IN ('match','adjudication')", name='ck_consensus_method_valid'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['final_disease_grading_id'], ['disease_gradings.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['grading_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_consensus_method'), 'consensus', ['method'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('grader_user_id', sa.Integer(), nullable=False),
    sa.Column('role_slot', sa.String(length=16), nullable=False),
    sa.Column('disease_grading_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('selected_features_json', sa.Text(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=True),
    sa.Column('grade_name', sa.String(length=64), nullable=True),
    sa.Column('grade_description', sa.Text(), nullable=True),
    sa.Column('ai_model_id', sa.Integer(), nullable=True),
    sa.Column('ai_model_name', sa.String(length=255), nullable=True),
    sa.Column('ai_model_version', sa.String(length=64), nullable=True),
    sa.CheckConstraint("role_slot IN ('resident','resident2','arbitrator','ai','review')", name='ck_grade_role_slot_valid'),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disease_grading_id'], ['disease_gradings.id'], ),
    sa.ForeignKeyConstraint(['grader_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['grading_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'grader_user_id', 'role_slot', name='uq_grade_task_user_slot')
    )
    op.create_index('ix_grade_task_slot', 'grades', ['task_id', 'role_slot'], unique=False)
    op.create_index('ix_grade_user_slot', 'grades', ['grader_user_id', 'role_slot'], unique=False)
    op.create_index(op.f('ix_grades_ai_model_id'), 'grades', ['ai_model_id'], unique=False)
    op.create_index(op.f('ix_grades_disease_grading_id'), 'grades', ['disease_grading_id'], unique=False)
    op.create_index(op.f('ix_grades_grader_user_id'), 'grades', ['grader_user_id'], unique=False)
    op.create_index(op.f('ix_grades_role_slot'), 'grades', ['role_slot'], unique=False)
    op.create_index(op.f('ix_grades_task_id'), 'grades', ['task_id'], unique=False)
    op.create_table('intra_rater_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('grader_user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('lab_unit_id', sa.Integer(), nullable=False),
    sa.Column('encounter_file_id', sa.Integer(), nullable=True),
    sa.Column('direct_image_upload_id', sa.Integer(), nullable=True),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['intra_rater_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['direct_image_upload_id'], ['direct_image_uploads.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['encounter_file_id'], ['encounter_files.id'], ),
    sa.ForeignKeyConstraint(['grader_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_unit_id'], ['lab_units.id'], ),
    sa.ForeignKeyConstraint(['source_task_id'], ['grading_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intra_rater_tasks_batch_id'), 'intra_rater_tasks', ['batch_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_direct_image_upload_id'), 'intra_rater_tasks', ['direct_image_upload_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_disease_id'), 'intra_rater_tasks', ['disease_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_encounter_file_id'), 'intra_rater_tasks', ['encounter_file_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_grader_user_id'), 'intra_rater_tasks', ['grader_user_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_lab_unit_id'), 'intra_rater_tasks', ['lab_unit_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_source_task_id'), 'intra_rater_tasks', ['source_task_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_state'), 'intra_rater_tasks', ['state'], unique=False)
    op.create_index(op.f('ix_intra_rater_tasks_uuid'), 'intra_rater_tasks', ['uuid'], unique=True)
    op.create_table('task_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_slot', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['grading_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_tracker_role_slot'), 'task_tracker', ['role_slot'], unique=False)
    op.create_index(op.f('ix_task_tracker_task_id'), 'task_tracker', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_tracker_user_id'), 'task_tracker', ['user_id'], unique=False)
    op.create_table('intra_rater_grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('grader_user_id', sa.Integer(), nullable=False),
    sa.Column('disease_grading_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('selected_features_json', sa.Text(), nullable=True),
    sa.Column('time_taken', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=True),
    sa.Column('grade_name', sa.String(length=64), nullable=True),
    sa.Column('grade_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['intra_rater_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disease_grading_id'], ['disease_gradings.id'], ),
    sa.ForeignKeyConstraint(['grader_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['intra_rater_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intra_rater_grades_batch_id'), 'intra_rater_grades', ['batch_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_grades_disease_grading_id'), 'intra_rater_grades', ['disease_grading_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_grades_grader_user_id'), 'intra_rater_grades', ['grader_user_id'], unique=False)
    op.create_index(op.f('ix_intra_rater_grades_task_id'), 'intra_rater_grades', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intra_rater_grades_task_id'), table_name='intra_rater_grades')
    op.drop_index(op.f('ix_intra_rater_grades_grader_user_id'), table_name='intra_rater_grades')
    op.drop_index(op.f('ix_intra_rater_grades_disease_grading_id'), table_name='intra_rater_grades')
    op.drop_index(op.f('ix_intra_rater_grades_batch_id'), table_name='intra_rater_grades')
    op.drop_table('intra_rater_grades')
    op.drop_index(op.f('ix_task_tracker_user_id'), table_name='task_tracker')
    op.drop_index(op.f('ix_task_tracker_task_id'), table_name='task_tracker')
    op.drop_index(op.f('ix_task_tracker_role_slot'), table_name='task_tracker')
    op.drop_table('task_tracker')
    op.drop_index(op.f('ix_intra_rater_tasks_uuid'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_state'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_source_task_id'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_lab_unit_id'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_grader_user_id'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_encounter_file_id'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_disease_id'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_direct_image_upload_id'), table_name='intra_rater_tasks')
    op.drop_index(op.f('ix_intra_rater_tasks_batch_id'), table_name='intra_rater_tasks')
    op.drop_table('intra_rater_tasks')
    op.drop_index(op.f('ix_grades_task_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_role_slot'), table_name='grades')
    op.drop_index(op.f('ix_grades_grader_user_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_disease_grading_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_ai_model_id'), table_name='grades')
    op.drop_index('ix_grade_user_slot', table_name='grades')
    op.drop_index('ix_grade_task_slot', table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_consensus_method'), table_name='consensus')
    op.drop_table('consensus')
    op.drop_index('ix_image_gradings_image_user_role_for', table_name='image_gradings')
    op.drop_index(op.f('ix_image_gradings_grader_user_id'), table_name='image_gradings')
    op.drop_index(op.f('ix_image_gradings_grader_role'), table_name='image_gradings')
    op.drop_index(op.f('ix_image_gradings_graded_for'), table_name='image_gradings')
    op.drop_index(op.f('ix_image_gradings_encounter_file_id'), table_name='image_gradings')
    op.drop_index('ix_image_gradings_direct_user_role_for', table_name='image_gradings')
    op.drop_index(op.f('ix_image_gradings_direct_image_upload_id'), table_name='image_gradings')
    op.drop_table('image_gradings')
    op.drop_index('ix_task_disease_lab_state', table_name='grading_tasks')
    op.drop_index(op.f('ix_grading_tasks_uuid'), table_name='grading_tasks')
    op.drop_index(op.f('ix_grading_tasks_state'), table_name='grading_tasks')
    op.drop_index(op.f('ix_grading_tasks_lab_unit_id'), table_name='grading_tasks')
    op.drop_index(op.f('ix_grading_tasks_encounter_file_id'), table_name='grading_tasks')
    op.drop_index(op.f('ix_grading_tasks_disease_id'), table_name='grading_tasks')
    op.drop_index(op.f('ix_grading_tasks_direct_image_upload_id'), table_name='grading_tasks')
    op.drop_index(op.f('ix_grading_tasks_ad_hoc_id'), table_name='grading_tasks')
    op.drop_table('grading_tasks')
    op.drop_index(op.f('ix_glaucoma_results_cleaned_report_uuid'), table_name='glaucoma_results_cleaned')
    op.drop_index(op.f('ix_glaucoma_results_cleaned_patient_encounter_id'), table_name='glaucoma_results_cleaned')
    op.drop_index(op.f('ix_glaucoma_results_cleaned_glaucoma_report_id'), table_name='glaucoma_results_cleaned')
    op.drop_table('glaucoma_results_cleaned')
    op.drop_index(op.f('ix_job_items_uploader_username'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_uploader_user_id'), table_name='job_items')
    op.drop_index(op.f('ix_job_items_job_id'), table_name='job_items')
    op.drop_table('job_items')
    op.drop_index(op.f('ix_glaucoma_reports_uuid'), table_name='glaucoma_reports')
    op.drop_table('glaucoma_reports')
    op.drop_index(op.f('ix_encounter_files_uuid'), table_name='encounter_files')
    op.drop_index(op.f('ix_encounter_files_lab_unit_id'), table_name='encounter_files')
    op.drop_index(op.f('ix_encounter_files_eye_side'), table_name='encounter_files')
    op.drop_table('encounter_files')
    op.drop_index(op.f('ix_encounter_file_pdfs_uuid'), table_name='encounter_file_pdfs')
    op.drop_index('ix_encounter_file_pdfs_patient_encounter_id', table_name='encounter_file_pdfs')
    op.drop_index(op.f('ix_encounter_file_pdfs_lab_unit_id'), table_name='encounter_file_pdfs')
    op.drop_index(op.f('ix_encounter_file_pdfs_eye_side'), table_name='encounter_file_pdfs')
    op.drop_table('encounter_file_pdfs')
    op.drop_index(op.f('ix_direct_image_verifications_verified_status'), table_name='direct_image_verifications')
    op.drop_index(op.f('ix_direct_image_verifications_verified_by_id'), table_name='direct_image_verifications')
    op.drop_index(op.f('ix_direct_image_verifications_image_upload_id'), table_name='direct_image_verifications')
    op.drop_table('direct_image_verifications')
    op.drop_index(op.f('ix_diabetic_retinopathy_reports_uuid'), table_name='diabetic_retinopathy_reports')
    op.drop_table('diabetic_retinopathy_reports')
    op.drop_table('user_lab_units')
    op.drop_index('ix_user_dur_user_active', table_name='user_disease_unit_role')
    op.drop_index('ix_user_dur_unit_disease', table_name='user_disease_unit_role')
    op.drop_index(op.f('ix_user_disease_unit_role_user_id'), table_name='user_disease_unit_role')
    op.drop_index(op.f('ix_user_disease_unit_role_lab_unit_id'), table_name='user_disease_unit_role')
    op.drop_index(op.f('ix_user_disease_unit_role_disease_id'), table_name='user_disease_unit_role')
    op.drop_table('user_disease_unit_role')
    op.drop_index(op.f('ix_patient_encounters_lab_unit_id'), table_name='patient_encounters')
    op.drop_index(op.f('ix_patient_encounters_glaucoma_verified_status'), table_name='patient_encounters')
    op.drop_index(op.f('ix_patient_encounters_encounter_verified_status'), table_name='patient_encounters')
    op.drop_index(op.f('ix_patient_encounters_dr_verified_status'), table_name='patient_encounters')
    op.drop_index(op.f('ix_patient_encounters_capture_date_dt'), table_name='patient_encounters')
    op.drop_table('patient_encounters')
    op.drop_index(op.f('ix_notification_reads_user_id'), table_name='notification_reads')
    op.drop_index(op.f('ix_notification_reads_notification_id'), table_name='notification_reads')
    op.drop_table('notification_reads')
    op.drop_index(op.f('ix_jobs_uploader_username'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_uploader_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_lab_unit_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_intra_rater_batches_normal_grade_id'), table_name='intra_rater_batches')
    op.drop_index(op.f('ix_intra_rater_batches_lab_unit_id'), table_name='intra_rater_batches')
    op.drop_index(op.f('ix_intra_rater_batches_disease_id'), table_name='intra_rater_batches')
    op.drop_index(op.f('ix_intra_rater_batches_created_by_user_id'), table_name='intra_rater_batches')
    op.drop_index(op.f('ix_intra_rater_batches_created_at'), table_name='intra_rater_batches')
    op.drop_table('intra_rater_batches')
    op.drop_index('ix_gradings_features_grading_order', table_name='gradings_features')
    op.drop_index(op.f('ix_gradings_features_disease_grading_id'), table_name='gradings_features')
    op.drop_table('gradings_features')
    op.drop_index('ix_diu_uploader_created', table_name='direct_image_uploads')
    op.drop_index('ix_diu_is_pregraded', table_name='direct_image_uploads')
    op.drop_index('ix_diu_folder_created', table_name='direct_image_uploads')
    op.drop_index('ix_diu_content_hash', table_name='direct_image_uploads')
    op.drop_index(op.f('ix_direct_image_uploads_uuid'), table_name='direct_image_uploads')
    op.drop_index(op.f('ix_direct_image_uploads_uploader_id'), table_name='direct_image_uploads')
    op.drop_index(op.f('ix_direct_image_uploads_folder_rel'), table_name='direct_image_uploads')
    op.drop_index(op.f('ix_direct_image_uploads_file_hash'), table_name='direct_image_uploads')
    op.drop_index(op.f('ix_direct_image_uploads_created_at'), table_name='direct_image_uploads')
    op.drop_table('direct_image_uploads')
    op.drop_index(op.f('ix_viewer_settings_user_id'), table_name='viewer_settings')
    op.drop_table('viewer_settings')
    op.drop_index(op.f('ix_viewer_presets_user_id'), table_name='viewer_presets')
    op.drop_table('viewer_presets')
    op.drop_index('ix_user_roles_user', table_name='user_roles')
    op.drop_index('ix_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_notifications_sender_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('lab_units')
    op.drop_index(op.f('ix_flask_sessions_user_id'), table_name='flask_sessions')
    op.drop_index(op.f('ix_flask_sessions_expiry'), table_name='flask_sessions')
    op.drop_table('flask_sessions')
    op.drop_index('ix_disease_gradings_disease_order', table_name='disease_gradings')
    op.drop_table('disease_gradings')
    op.drop_index(op.f('ix_ad_hoc_task_creations_created_by_id'), table_name='ad_hoc_task_creations')
    op.drop_index(op.f('ix_ad_hoc_task_creations_created_at'), table_name='ad_hoc_task_creations')
    op.drop_table('ad_hoc_task_creations')
    op.drop_table('zip_files')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_password_reset_attempts_ip_date', table_name='password_reset_attempts')
    op.drop_index('ix_password_reset_attempts_email_date', table_name='password_reset_attempts')
    op.drop_index(op.f('ix_password_reset_attempts_email'), table_name='password_reset_attempts')
    op.drop_index(op.f('ix_password_reset_attempts_attempted_at'), table_name='password_reset_attempts')
    op.drop_table('password_reset_attempts')
    op.drop_index('ix_login_attempts_username_created', table_name='login_attempts')
    op.drop_index('ix_login_attempts_ip_created', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_ip_locks_ip_address'), table_name='ip_locks')
    op.drop_table('ip_locks')
    op.drop_table('hospitals')
    op.drop_table('diseases')
    op.drop_table('cameras')
    op.drop_table('areas')
    op.drop_table('app_settings')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
