"""Canonical action identifiers.  This module has no application imports."""

from enum import Enum

_LEGACY_NAMES = [
    "account.password.change",
    "account.profile.update",
    "account.profile.view",
    "ad_hoc_task.create",
    "ad_hoc_task.delete",
    "ad_hoc_task.view",
    "admin.dashboard.view",
    "admin.grading_eligibility.manage",
    "admin.lookup.manage",
    "admin.s3.manage",
    "admin.security.view",
    "admin.system.manage",
    "admin.upload_profiles.manage",
    "admin.users.manage",
    "admin.users.view",
    "analytics.encounters.view",
    "analytics.hospital_dashboard.view",
    "analytics.kpi.direct_files.rows",
    "analytics.kpi.direct_files.view",
    "analytics.kpi.encounter_files.rows",
    "analytics.kpi.encounter_files.view",
    "analytics.upload_stats.view",
    "api.lookups.manage",
    "api.lookups.view",
    "api.mobile.session.manage",
    "api.ocr.manage",
    "api.viewer_settings.manage",
    "audit.data_quality.view",
    "auth.login",
    "auth.logout",
    "auth.password_reset",
    "auth.reauth",
    "dashboard.home.view",
    "dashboard.view",
    "dataset.curation.update",
    "dataset.curation.view",
    "dataset.delete",
    "dataset.export.create",
    "dataset.export.download",
    "dataset.finalize",
    "dataset.public_download",
    "dataset.share.manage",
    "docs.api.view",
    "glaucoma_ai.result.view",
    "glaucoma_ai.upload.create",
    "glaucoma_ai.workspace.view",
    "grading.arbitrator.submit",
    "grading.grades.view",
    "grading.resident.submit",
    "grading.resident2.submit",
    "help.view",
    "inference.wai.retry",
    "inference.wai.rows",
    "inference.wai.run",
    "inference.wai.summary",
    "intra_rater.batch.create",
    "intra_rater.batch.view",
    "intra_rater.kpi.view",
    "intra_rater.task.submit",
    "intra_rater.task.view",
    "jobs.regenerate",
    "jobs.result.view",
    "jobs.view",
    "media.image.view",
    "media.metadata.process",
    "media.metadata.read",
    "media.ocr_pii.process",
    "media.ocr_pii.read",
    "media.pdf.view",
    "media.thumbnail.view",
    "mobile.context.view",
    "mobile.field.encounter.capture",
    "mobile.field.encounter.view",
    "mobile.field.inference.run",
    "mobile.field.project.view",
    "mobile.session.revoke",
    "mobile.session.view",
    "mobile.upload.create",
    "notifications.update",
    "notifications.view",
    "preprocess.dashboard.view",
    "preprocess.image.update",
    "project.access.manage",
    "project.encountersets.browse",
    "project.encountersets.browse_pii",
    "project.upload.direct_image",
    "project.upload.encounter_set",
    "project.upload.pregraded",
    "project.upload.remidio",
    "project.upload.remidio_api_sync",
    "project.uploaders.manage",
    "project.view",
    "project.wai.results",
    "project.wai.run",
    "public.view",
    "reports.view",
    "review.discrepancy.export",
    "review.discrepancy.view",
    "review.regrade.adjudicate",
    "review.regrade_creator.manage",
    "review.task.submit",
    "review.task.view",
    "screenings.delete",
    "screenings.reprocess",
    "screenings.view",
    "search.view",
    "tasks.view",
    "tasks.viewer.view",
    "upload.direct.create",
    "upload.direct.edit_image",
    "upload.direct.view",
    "upload.pregraded.create",
    "upload.zip.create",
    "upload.zip.view",
    "verification.direct.update",
    "verification.direct.view",
    "verification.encounter_set.update",
    "verification.pregraded.update",
    "verification.pregraded.view",
    "verification.remidio.update",
    "verification.remidio.view",
]

ACTION_MIGRATION_MAP: dict[str, str] = {name: name for name in _LEGACY_NAMES}
ACTION_MIGRATION_MAP.update(
    {
        "auth.password_reset": "auth.password_reset.request",
        "notifications.view": "account.notifications.view",
        "notifications.update": "account.notifications.update",
        "mobile.session.view": "account.mobile_sessions.view",
        "mobile.session.revoke": "account.mobile_sessions.revoke",
        "api.viewer_settings.manage": "account.viewer_preferences.manage",
        "dashboard.home.view": "dashboard.view",
        "analytics.kpi.direct_files.view": "analytics.kpi.view",
        "analytics.kpi.encounter_files.view": "analytics.kpi.view",
        "upload.direct.create": "upload.create",
        "upload.zip.create": "upload.create",
        "project.upload.direct_image": "project.upload.create",
        "project.upload.encounter_set": "project.upload.create",
        "project.upload.remidio": "project.upload.create",
        "project.upload.remidio_api_sync": "project.upload.create",
        "verification.pregraded.view": "verification.direct.view",
        "verification.pregraded.update": "verification.direct.update",
        "media.thumbnail.view": "media.image.view",
    }
)

# Reset completion is a distinct credential-bearing action. It has no legacy
# equivalent because the former route used one action for request and consume.
_CANONICAL_ONLY = {
    "admin.system.operation",
    "admin.system.status.view",
    "admin.users.create",
    "admin.users.workspace.view",
    "admin.upload_profiles.update",
    "auth.mobile.logout",
    "auth.mobile.refresh",
    "auth.password_reset.complete",
    "authorization.catalogue.view",
    "authorization.grants.manage",
    "authorization.grants.view",
    "authorization.me.capabilities.view",
    "authorization.me.upload_options.view",
    "authorization.me.workspaces.view",
    "dataset.export.download_identifiers",
    "review.discrepancy.export_identifiers",
    "analytics.kpi.view",
    "dataset.curation.image.update",
    "dataset.export.grades",
    "inference.wai.retrospective.run",
    "media.metadata.raw.read",
    "mobile.field.project.sync",
    "mobile.field.projects.list",
    "mobile.session.detail.view",
    "mobile.session.list",
    "mobile.session.revoke",
    "mobile.upload.inference.retry",
    "mobile.upload.options.view",
    "mobile.upload.view",
    "notifications.send",
    "project.grader_allocations.enforcement.manage",
    "project.grader_allocations.manage",
    "project.grader_allocations.view",
    "project.grants.view",
    "project.encountersets.workspace.view",
    "project.encountersets.workspace.view_pii",
    "project.site_policy.manage",
    "project.upload.create",
    "project.upload.workspace.view",
    "public.analytics.view",
    "upload.create",
    "upload.direct.batch.update",
    "upload.direct.update",
    "upload.pregraded.workspace.view",
    "upload.workspace.view",
    "verification.encounter_set.view",
}
_CANONICAL_NAMES = sorted(set(ACTION_MIGRATION_MAP.values()) | _CANONICAL_ONLY)

Action = Enum(
    "Action",
    {name.upper().replace(".", "_"): name for name in _CANONICAL_NAMES},
    type=str,
)
ACTION_MANIFEST: frozenset[str] = frozenset(_CANONICAL_NAMES)
RETIRED_ACTIONS: dict[str, str] = {}


def action_from_name(value: str | Action) -> Action:
    """Convert a wire name to a canonical action; unknown values fail closed."""
    if isinstance(value, Action):
        return value
    try:
        return Action(value)
    except (ValueError, TypeError) as exc:
        raise ValueError(f"unknown authorization action: {value!r}") from exc
